---
- name: Remove existing logstash
  apt:
    package: logstash
    state: absent
    purge: yes
  when:
    - logging_upgrade | bool

- name: Remove /etc/init/logstash-web.override
  file:
    name: "/etc/init/logstash-web.override"
    state: absent
  when:
    - logging_upgrade | bool

- name: Register legacy logstash configuration files
  shell: "ls -1 /etc/logstash/conf.d"
  register: logstash_legacy_conf
  when:
    - logging_upgrade | bool

- name: Remove legacy logstash configuration files
  file:
    name: "/etc/logstash/conf.d/{{ item }}"
    state: absent
  with_items: "{{ logstash_legacy_conf.stdout_lines | default([]) }}"
  when:
    - logging_upgrade | bool

- name: Register legacy logstash patterns
  shell: "ls -1 /opt/logstash/patterns"
  register: logstash_legacy_patterns
  when:
    - logging_upgrade | bool

- name: Remove legacy logstash patterns
  file:
    name: "/opt/logstash/patterns/{{ item }}"
    state: absent
  with_items: "{{ logstash_legacy_conf.stdout_lines | default([]) }}"
  when:
    - logging_upgrade | bool

