---
- name: Add legacy apt repositories
  apt_repository:
    repo: "{{ item.repo }}"
    state: "{{ item.state }}"
  with_items: elasticsearch_legacy_apt_repos
  register: add_repos
  until: add_repos|success
  retries: 5
  delay: 2
  tags:
    - logging-upgrade
    - elasticsearch-upgrade

- name: Upgrade logstash to stable 1.7.x version
  apt:
    pkg: "{{ item }}"
    state: latest
    update_cache: yes
    cache_valid_time: 600
    upgrade: yes
    dpkg_options: "force-confold"
  register: install_apt_packages
  until: install_apt_packages|success
  retries: 5
  delay: 2
  with_items: elasticsearch_apt_packages
  tags:
    - logging-upgrade
    - elasticsearch-upgrade

- name: Drop log_test1 template
  shell: 'curl -sk -XDELETE {{ internal_lb_vip_address }}:{{ elasticsearch_http_port }}/_template/log_test1'
  when:
    - logging_upgrade | bool
  tags:
    - logging-upgrade
    - elasticsearch-upgrade

- name: Place legacy liberty template
  template:
    src: legacy-mapping.sh.j2
    dest: /opt/legacy-mapping.sh
    owner: root
    group: root
    mode: 755
  delegate_to: "{{ groups['elasticsearch_all'][0] }}"
  when:
    - logging_upgrade | bool
  tags:
    - logging-upgrade
    - elasticsearch-upgrade

- name: Install legacy liberty template
  shell: '/opt/legacy-mapping.sh'
  register: legacy_template_result
  delegate_to: "{{ groups['elasticsearch_all'][0] }}"
  when:
    - logging_upgrade | bool
  tags:
    - logging-upgrade
    - elasticsearch-upgrade

- name: Remove legacy liberty template
  file:
    name: '/opt/legacy-mapping.sh'
    state: absent
  delegate_to: "{{ groups['elasticsearch_all'][0] }}"
  when:
    - logging_upgrade | bool
  tags:
    - logging-upgrade
    - elasticsearch-upgrade

- name: Install Reindexing Plugin
  command: ./plugin -install {{ item }}
  args:
    chdir: /usr/share/elasticsearch/bin
    creates: /usr/share/elasticsearch/plugins/reindexing
  with_items:
    - org.codelibs/elasticsearch-reindexing/1.4.2
  when:
    - logging_upgrade | bool
  tags:
    - logging-upgrade
    - elasticsearch-upgrade

- name: Install reindexing wrapper script
  template:
    src: reindex-liberty.py.j2
    dest: /opt/reindex-liberty.py
    owner: root
    group: root
    mode: 755
  delegate_to: "{{ groups['elasticsearch_all'][0] }}"
  when:
    - logging_upgrade | bool
  tags:
    - logging-upgrade
    - elasticsearch-upgrade
    - elasticsearch-reindex

- name: Reindex legacy elasticsearch indices
  command: reindex-liberty.py --host "{{ hostvars[groups['elasticsearch_container'][0]]['container_address'] }}" --reindex
  args:
    chdir: /opt
  delegate_to: "{{ groups['elasticsearch_all'][0] }}"
  when:
    - logging_upgrade | bool
  tags:
    - logging-upgrade
    - elasticsearch-upgrade
    - elasticsearch-reindex

- name: Drop legacy elasticsearch indeices
  command: reindex-liberty.py --host "{{ hostvars[groups['elasticsearch_container'][0]]['container_address'] }}" --drop
  args:
    chdir: /opt
  delegate_to: "{{ groups['elasticsearch_all'][0] }}"
  when:
    - logging_upgrade | bool
  tags:
    - logging-upgrade
    - elasticsearch-upgrade
    - elasticsearch-reindex

