---
# Copyright 2014, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Get entity ID for physical_host
  shell: raxmon-entities-list  | grep "label={{ physical_host|quote }}{{ maas_fqdn_extension }} " | sed -e 's/^.* id=\(.*\) label=.*$/\1/g'
  register: entity_id
  delegate_to: "{{ physical_host }}"

- name: Validate if check exists
  shell: raxmon-checks-list --entity-id {{ entity_id.stdout|quote }} | grep "label={{ check_name|quote }}--{{ ansible_hostname|quote }}"
  register: check_exists
  ignore_errors: True
  delegate_to: "{{ physical_host }}"

- name: Create check if it does not exist
  command: raxmon-checks-create --entity-id {{ entity_id.stdout }} --type agent.plugin --label {{ check_name }}--{{ ansible_hostname }} --details {{ check_details }} --period {{ check_period }} --timeout {{ check_timeout }}
  when: check_exists|failed
  delegate_to: "{{ physical_host }}"

- name: Get check ID for newly created check
  shell: raxmon-checks-list --entity-id {{ entity_id.stdout|quote }} | grep "label={{ check_name|quote }}--{{ ansible_hostname|quote }}" | sed -e 's/^.* id=\(.*\) label=.*$/\1/g'
  register: check_id
  delegate_to: "{{ physical_host }}"

- name: Create alarm if it does not exist
  shell: a=$(raxmon-alarms-list --entity-id {{ entity_id.stdout|quote }} | grep -c "{{ [item[0].name, (['osd', item[1]] | join('.'))] | join('_') | quote }}--{{ ansible_hostname|quote }}"); if [ $a -lt 1 ]; then raxmon-alarms-create --entity-id {{ entity_id.stdout|quote }} --check-id {{ check_id.stdout|quote }} --notification-plan {{ maas_notification_plan }} --label {{ [item[0].name, (['osd', item[1]] | join('.'))] | join('_') | quote }}--{{ ansible_hostname|quote }} --criteria {{ item[0].criteria | regex_replace('^(.*)OSD(.*)$', (['\\1', 'osd.', item[1], '\\2'] | join(''))) | quote }}; fi
  delegate_to: "{{ physical_host }}"
  when: alarms is defined
  with_nested:
    - alarms
    - ceph_osd_host['osd_ids']
